---
swagger: "2.0"
schemes:
- "https"
paths:
  /:
    get:
      produces:
        - "text/html"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${LAMBDA_INVOCATION_URI}"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
  /send:
    post:
      produces:
        - "application/json"
      consumes:
        - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${LAMBDA_INVOCATION_URI}"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"

definitions:
  Empty:
    type: "object"
    title: "Empty Schema"