---
swagger: "2.0"
schemes:
- "https"
paths:
  /message:
    post:
      produces:
        - "application/xml"
      consumes:
        - "application/x-www-form-urlencoded"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${LAMBDA_INVOCATION_URI}"
        responses:
          default:
            statusCode: "200"
            responseTemplates:
              application/xml: "$input.path('$')"
        passthroughBehavior: "when_no_templates"
        type: aws
        requestTemplates:
          application/x-www-form-urlencoded: |
            #set($httpPost = $input.path('$').split("&"))
            {
            #foreach( $kvPair in $httpPost )
              #set($kvTokenised = $kvPair.split("="))
              #if( $kvTokenised.size() > 1 )
                "$kvTokenised[0]" : "$kvTokenised[1]"#if( $foreach.hasNext ),#end
              #else
                "$kvTokenised[0]" : ""#if( $foreach.hasNext ),#end
              #end
            #end
            }
      x-amazon-apigateway-gateway-responses:
        
definitions:
  Empty: {}